version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: patrick
      POSTGRES_PASSWORD: example
      POSTGRES_DB: fizikdb



  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"


  api:
    build: .
    command: ["uvicorn", "api.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./api:/app/api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db